name: datacamp
channels:
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- appnope=0.1.0=py36_0
- backports=1.0=py36_1
- backports.functools_lru_cache=1.4=py36_1
- blas=1.1=openblas
- bleach=2.0.0=py_1
- ca-certificates=2017.11.5=0
- certifi=2017.11.5=py36_0
- cycler=0.10.0=py36_0
- decorator=4.1.2=py36_0
- entrypoints=0.2.3=py36_1
- freetype=2.8.1=0
- html5lib=1.0.1=py_0
- icu=58.2=0
- ipykernel=4.8.0=py36_0
- ipython=6.2.1=py36_1
- ipython_genutils=0.2.0=py36_0
- ipywidgets=7.1.1=py36_0
- jedi=0.11.1=py36_0
- jinja2=2.10=py36_0
- jpeg=9b=2
- jsonschema=2.6.0=py36_1
- jupyter=1.0.0=py36_0
- jupyter_client=5.2.2=py36_0
- jupyter_console=5.2.0=py36_0
- jupyter_core=4.4.0=py_0
- libgfortran=3.0.0=0
- libpng=1.6.34=0
- libsodium=1.0.15=1
- markupsafe=1.0=py36_0
- matplotlib=2.1.2=py36_0
- mistune=0.8.3=py_0
- nbconvert=5.3.1=py_1
- nbformat=4.4.0=py36_0
- ncurses=5.9=10
- notebook=5.4.0=py36_0
- numpy=1.14.0=py36_blas_openblas_200
- openblas=0.2.20=7
- openssl=1.0.2n=0
- pandas=0.22.0=py36_0
- pandoc=2.1.1=0
- pandocfilters=1.4.1=py36_0
- parso=0.1.1=py_0
- patsy=0.5.0=py36_0
- pexpect=4.3.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- prompt_toolkit=1.0.15=py36_0
- ptyprocess=0.5.2=py36_0
- pygments=2.2.0=py36_0
- pyparsing=2.2.0=py36_0
- pyqt=5.6.0=py36_4
- python=3.6.4=0
- python-dateutil=2.6.1=py36_0
- pytz=2017.3=py_2
- pyzmq=16.0.2=py36_3
- qt=5.6.2=h9e3eb04_4
- qtconsole=4.3.1=py36_0
- readline=7.0=0
- scipy=1.0.0=py36_blas_openblas_201
- seaborn=0.8.1=py36_0
- send2trash=1.4.2=py_0
- setuptools=38.4.0=py36_0
- simplegeneric=0.8.1=py36_0
- sip=4.18=py36_1
- six=1.11.0=py36_1
- sqlite=3.20.1=2
- statsmodels=0.8.0=py36_0
- terminado=0.8.1=py36_0
- testpath=0.3.1=py36_0
- tk=8.6.7=0
- tornado=4.5.3=py36_0
- traitlets=4.3.2=py36_0
- wcwidth=0.1.7=py36_0
- webencodings=0.5=py36_0
- wheel=0.30.0=py36_2
- widgetsnbextension=3.1.3=py36_0
- xz=5.2.3=0
- zeromq=4.2.1=1
- zlib=1.2.11=0
- pip:
  - arrow==0.10.0
  - backports.functools-lru-cache==1.4
  - binaryornot==0.4.3
  - chardet==3.0.4
  - click==6.7
  - cookiecutter==1.5.1
  - ipython-genutils==0.2.0
  - jinja2-time==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - poyo==0.4.1
  - prompt-toolkit==1.0.15
  - sqlalchemy==1.2.5
  - whichcraft==0.4.1
prefix: /Users/franciscosalas/miniconda3/envs/datacamp

