name: datacamp
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - nltk=3.3.0=py36_0
  - bokeh=0.12.14=py36_0
  - decorator=4.2.1=py36_0
  - ipykernel=4.8.0=py36_0
  - ipywidgets=7.1.1=py36_0
  - jedi=0.11.1=py36_0
  - jupyter_client=5.2.2=py36_0
  - nb_conda_kernels=2.1.0=py36_0
  - notebook=5.3.1=py36_2
  - patsy=0.5.0=py36_0
  - pexpect=4.3.1=py36_0
  - setuptools=38.4.0=py36_0
  - terminado=0.8.1=py36_0
  - tornado=4.5.3=py36_0
  - widgetsnbextension=3.1.0=py36_0
  - asn1crypto=0.24.0=py36_0
  - bleach=2.1.2=py36_0
  - boto=2.49.0=py36_0
  - boto3=1.7.62=py36_1
  - botocore=1.10.62=py36_0
  - ca-certificates=2017.08.26=h1d4fec5_0
  - certifi=2018.1.18=py36_0
  - cffi=1.11.5=py36h9745a5d_0
  - chardet=3.0.4=py36_1
  - cryptography=2.2.1=py36h14c3975_0
  - cycler=0.10.0=py36h93f1223_0
  - cymem=1.31.2=py36h6bb024c_0
  - cytoolz=0.8.2=py36h708bfd4_0
  - dbus=1.12.2=hd3e2b69_0
  - dill=0.2.8.2=py36_0
  - docutils=0.14=py36_0
  - entrypoints=0.2.3=py36h1aec115_2
  - expat=2.2.5=he0dffb1_0
  - fontconfig=2.12.4=h88586e7_1
  - freetype=2.8=hab7d2ae_1
  - gensim=3.4.0=py36h14c3975_0
  - glib=2.53.6=h5d9569c_2
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - html5lib=1.0.1=py36h2f9c1c0_0
  - icu=58.2=h9c2bf20_1
  - idna=2.7=py36_0
  - intel-openmp=2018.0.0=hc7b2577_8
  - ipython=6.2.1=py36h88c514a_1
  - ipython_genutils=0.2.0=py36hb52b0d5_0
  - jinja2=2.10=py36ha16c418_0
  - jmespath=0.9.3=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=2.6.0=py36h006f8b5_0
  - jupyter=1.0.0=py36h9896ce5_0
  - jupyter_console=5.2.0=py36he59e554_1
  - jupyter_core=4.4.0=py36h7c827e3_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=h7cc24e2_2
  - libgfortran-ng=7.2.0=h9f7466a_2
  - libpng=1.6.34=hb9fc6fc_0
  - libsodium=1.0.15=hf101ebd_0
  - libstdcxx-ng=7.2.0=h7a57d05_2
  - libxcb=1.12=hcd93eb1_4
  - libxml2=2.9.7=h26e45fe_0
  - markupsafe=1.0=py36hd9260cd_1
  - matplotlib=2.1.2=py36h0e671d2_0
  - mistune=0.8.3=py36_0
  - mkl=2018.0.1=h19d6760_4
  - msgpack-numpy=0.4.3=py36_0
  - msgpack-python=0.5.6=py36h6bb024c_0
  - murmurhash=0.28.0=py36hf484d3e_0
  - nbconvert=5.3.1=py36hb41ffb7_0
  - nbformat=4.4.0=py36h31c9010_0
  - ncurses=6.0=h9df7e31_2
  - numpy=1.14.0=py36h3dfced4_1
  - openssl=1.0.2n=hb7f436b_0
  - packaging=17.1=py36_0
  - pandas=0.22.0=py36hf484d3e_0
  - pandoc=1.19.2.1=hea2e7c5_1
  - pandocfilters=1.4.2=py36ha6701b7_1
  - parso=0.1.1=py36h35f843b_0
  - pathlib=1.0.1=py36_0
  - pcre=8.41=hc27e229_1
  - pickleshare=0.7.4=py36h63277f8_0
  - pip=9.0.1=py36h6c6f9ce_4
  - plac=0.9.6=py36_0
  - preshed=1.0.0=py36hf484d3e_0
  - prompt_toolkit=1.0.15=py36h17d85b1_0
  - ptyprocess=0.5.2=py36h69acd42_0
  - pycparser=2.18=py36_1
  - pygments=2.2.0=py36h0d3125c_0
  - pyopenssl=18.0.0=py36_0
  - pyparsing=2.2.0=py36hee85983_1
  - pyqt=5.6.0=py36h0386399_5
  - pysocks=1.6.8=py36_0
  - python=3.6.4=hc3d631a_1
  - python-dateutil=2.6.1=py36h88d3b88_1
  - pytz=2017.3=py36h63b9c63_0
  - pyyaml=3.12=py36hafb9ca4_1
  - pyzmq=16.0.3=py36he2533c7_0
  - qt=5.6.2=h974d657_12
  - qtconsole=4.3.1=py36h8f73b5b_0
  - readline=7.0=ha6073c6_4
  - regex=2018.06.21=py36h14c3975_0
  - requests=2.19.1=py36_0
  - s3transfer=0.1.13=py36_0
  - scipy=1.0.0=py36hbf646e7_0
  - seaborn=0.8.1=py36hfad7ec4_0
  - send2trash=1.4.2=py36_0
  - simplegeneric=0.8.1=py36h2cb9092_0
  - sip=4.18.1=py36h51ed4ed_2
  - six=1.11.0=py36h372c433_1
  - smart_open=1.6.0=py36_0
  - spacy=2.0.11=py36h04863e7_2
  - sqlite=3.22.0=h1bed415_0
  - statsmodels=0.8.0=py36h8533d0b_0
  - termcolor=1.1.0=py36_1
  - testpath=0.3.1=py36h8cadb63_0
  - thinc=6.10.1=py36hd61447b_0
  - tk=8.6.7=hc745277_3
  - toolz=0.9.0=py36_0
  - tqdm=4.24.0=py36_0
  - traitlets=4.3.2=py36h674d592_0
  - ujson=1.35=py36h14c3975_0
  - urllib3=1.23=py36_0
  - wcwidth=0.1.7=py36hdf4376a_0
  - webencodings=0.5.1=py36h800622e_1
  - wheel=0.30.0=py36hfd4bba0_1
  - wrapt=1.10.11=py36h14c3975_2
  - xz=5.2.3=h55aa19d_2
  - yaml=0.1.7=had09818_2
  - zeromq=4.2.2=hbedb6e5_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - en-core-web-sm==2.0.0
    - et-xmlfile==1.0.1
    - jdcal==1.3
    - lxml==4.1.1
    - morfessor==2.0.4
    - openpyxl==2.5.0
    - pandas-datareader==0.6.0
    - pillow==5.0.0
    - polyglot==16.7.4
    - psycopg2==2.7.4
    - pycld2==0.31
    - pyicu==2.0.3
    - pymysql==0.8.0
    - requests-file==1.4.3
    - requests-ftp==0.3.1
    - scikit-learn==0.19.1
    - sklearn==0.0
    - sqlalchemy==1.2.5
    - xlrd==1.1.0
prefix: /home/frank/miniconda3/envs/datacamp

